# Site settings
title:        "ariissleeping"
description:  "website with cubing stuffs and other stuff"
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "http://ariissleeping.github.io" # the base hostname & protocol for your site
permalink:    /:year/:title
github:       "ariissleeping"
instagram:    "ariissleeping"
email:        "ariissleeping.business@gmail.com"
disqus-id:    "" #leave blank if you dont want comments.
# Google Analytics
google_analytics: UA-138574133-1

# Build settings
markdown:     kramdown
sass:
    style: :compressed
